services:

  proxy_server:
    build:
      context: ./src/ProxyServer
    env_file:
      - ./.env.dev
    ports:
      - "8765:5000"
    depends_on:
      - player_api
      - stats_api
      - discord_bot
    environment:
      DISCORD_BOT_URL: http://discord_bot:5003
      STATS_API_URL: http://stats_api:5002
      PLAYER_API_URL: http://player_api:5001
    expose:
      - 5000

  player_api:
    build:
      context: ./src/PlayerAPI
    env_file:
      - ./.env.dev
    expose:
      - 5001

  stats_api:
    build:
      context: ./src/StatsAPI
    env_file:
      - ./.env.dev
    volumes:
      - stats_db:/db
    expose:
      - 5002

  discord_bot:
    build:
      context: ./src/DiscordBot
    env_file:
      - ./.env.dev
    volumes:
      - discord_bot_config:/db
    expose:
      - 5003

volumes:
  stats_db:
  discord_bot_config:
