services:
  discord_bot:
    build:
      context: ./src/DiscordBot
    env_file:
      - ./.env.dev
    volumes:
      - discord_bot_config:/db
  player_api:
    build:
      context: ./src/PlayerAPI
    env_file:
      - ./.env.dev
  stats_api:
    build:
      context: ./src/StatsAPI
    env_file:
      - ./.env.dev
    volumes:
      - stats_db:/db
  proxy_server:
    build:
      context: ./src/ProxyServer
    env_file:
      - ./.env.dev
    ports:
      - "5000:8765"
    depends_on:
      - player_api
      - stats_api
      - discord_bot

volumes:
  stats_db:
  discord_bot_config:
